### ISSUE TITLE
api文档的生成问题

### ISSUE THREAD

**Issue by L-Super** [CefView/QCefViewDoc#4]
使用doxygen生成xml文档，再使用[moxygen](https://github.com/sourcey/moxygen)工具转换为md文档？moxygen需要node环境？
@tishion

**Comment by tishion** [comment]
需要，并且moxygen是我修改过的，原版没人维护了，不能满足项目要求

**Comment by L-Super** [comment]
能不能介绍一下怎么使用？

**Comment by tishion** [comment]
这个项目是一个基于nodejs的纯前端项目，facebook开源的专门用于搭建文档型站点的框架https://docusaurus.io/
QCefViewDoc这个项目下的目录结构以及功能：
|   |   | 
|---|---|
| [.github/workflows](https://github.com/CefView/QCefViewDoc/tree/master/.github/workflows) | GitHub Action目录，用于构建和部署  |  
| [docs](https://github.com/CefView/QCefViewDoc/tree/master/docs)  | 站点内容，都是Markdown文件  |
| [i18n](https://github.com/CefView/QCefViewDoc/tree/master/i18n)  | 多语言翻译，对应上面doc目录下的每个内容页面，都可以创建一个对应语言的翻译  | 
| [src](https://github.com/CefView/QCefViewDoc/tree/master/src)  | 前端源码，如果没有前端经验请勿动  | 
| [static](https://github.com/CefView/QCefViewDoc/tree/master/static)  | 前端静态资源文件  | 

如果仅仅是为了更新文档，只需要改动docs目录下的markdown文件，以及对应的对语言的翻译文件（也是markdown文件）

docs目录下有以下三个子目录
[guide](https://github.com/CefView/QCefViewDoc/tree/master/docs/guide)
[intros](https://github.com/CefView/QCefViewDoc/tree/master/docs/intros)
以上两个子目录内的内容都是手写的

[reference](https://github.com/CefView/QCefViewDoc/tree/master/docs/reference)
这个目录内的内容是通过脚本生成的API文档，具体操作就是
1. 通过doxygen生成xml文件目录（Doxygen的配置文件[在QCefView项目的docs目录内](https://github.com/CefView/QCefView/blob/main/scripts/doxygen/Doxyfile)）

2. 通过moxygen把xml目录作为输入参数生成markdown文件。（可以把生成的xml目录复制到当前项目的根目录下，然后执行以下命令：
    > npm run moxygen -- -c -a -H -o "%s.md" xml
 使用得到的markdown文件替换reference目录下的文件

具体到nodejs前端项目的开发，你需要自己去学习。
