### ISSUE TITLE
英文API文档更新

### ISSUE THREAD

**Issue by L-Super** [CefView/QCefViewDoc#7]
翻译过程中，发现cefview的新修改的接口没有更新到文档

**Comment by tishion** [comment]
需要跑一下doxygen，先安装doxygen
然后在QCefView的目录下进行以下操作
```bat
@rem 切换到doxgen目录下
cd scripts\doxygen

@rem 执行doxgen 命令，无需任何参数
doxygen 

@rem 会生成xml目录
```

然后
clone本项目到QCefViewDoc

然后初始化项目
npm install

然后把xml目录复制到 QCefViewDoc的根目录下，执行以下命令
npm run moxygen -- -c -a -H -o "%s.md" xml

就会得到对应的md文件

**Comment by L-Super** [comment]
> 需要跑一下doxygen，先安装doxygen 然后在QCefView的目录下进行以下操作
> 
> ```batchfile
> @rem 切换到doxgen目录下
> cd scripts\doxygen
> 
> @rem 执行doxgen 命令，无需任何参数
> doxygen 
> 
> @rem 会生成xml目录
> ```
> 
> 然后 clone本项目到QCefViewDoc
> 
> 然后初始化项目 npm install
> 
> 然后把xml目录复制到 QCefViewDoc的根目录下，执行以下命令 npm run moxygen -- -c -a -H -o "%s.md" xml
> 
> 就会得到对应的md文件

`npm run moxygen -- -c -a -H -o "%s.md" xml`是调用的原版moxygen吗？我记得之前issue说moxygen原版不能满足要求

**Comment by tishion** [comment]
项目里引用的已经是修改版的了

**Comment by tishion** [comment]
你有遇到什么无法解决的问题吗？

**Comment by L-Super** [comment]
> 你有遇到什么无法解决的问题吗？

刚刚尝试更新了一版，没有问题。
